# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Aureliolo.steamship
PackageVersion: 0.4.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: steamship-0.4.0-x86_64-pc-windows-msvc\steamship.exe
  PortableCommandAlias: steamship
ReleaseDate: 2026-09-27
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Aureliolo/steamship/releases/download/v0.4.0/steamship-0.4.0-x86_64-pc-windows-msvc.zip
  InstallerSha256: 5AA720BC2F671FCCB0D76E0B5E6EE264F584BAA69393CB30BC98B9BCE9D226A2
ManifestType: installer
ManifestVersion: 1.12.0
